"use client";

import { useState } from "react";
import { motion } from "framer-motion";
import { Copy, Eye, EyeOff } from "lucide-react";

export function PurchasedWebsites({ purchases }: { purchases: any[] }) {
  const [visible, setVisible] = useState<Record<string, boolean>>({});
  const copy = (value: string) => navigator.clipboard.writeText(value);
  const fields = (account: any) => [["Email", account.email], ["Password", account.password], ["Phone", account.recovery_phone], ["2FA", account.two_factor_secret]].filter(([, value]) => value);

  return <motion.section initial={{ opacity: 0, y: 12 }} animate={{ opacity: 1, y: 0 }} className="app-surface p-4 sm:p-5"><h2 className="mb-5 text-base font-extrabold text-[#0a2342]">My purchased accounts</h2>{!purchases?.length ? <p className="py-8 text-center text-xs text-slate-500">No purchased accounts yet. Visit the marketplace to get started.</p> : <div className="space-y-3">{purchases.map((purchase, index) => { const account = purchase.account; const shown = visible[purchase.id]; return <motion.article key={purchase.id} initial={{ opacity: 0, x: -10 }} animate={{ opacity: 1, x: 0 }} transition={{ delay: index * .04 }} className="rounded-xl border border-slate-200 p-3 sm:p-4"><div className="flex items-start justify-between gap-3"><div className="min-w-0"><h3 className="text-sm font-extrabold text-slate-800">{account.username}</h3><p className="mt-1 break-all text-[11px] text-slate-500">{account.email}</p><span className="mt-2 inline-flex rounded-full bg-blue-50 px-2.5 py-1 text-[10px] font-bold capitalize text-blue-700">{account.platform}</span></div><div className="shrink-0 text-right"><p className="text-[10px] text-slate-400">Purchased</p><p className="mt-1 text-[11px] font-bold text-slate-700">{new Date(purchase.created_at).toLocaleDateString()}</p></div></div><div className="mt-4 border-t border-slate-100 pt-3"><div className="flex items-center justify-between"><p className="text-xs font-bold text-slate-700">Credentials</p><button type="button" onClick={() => setVisible((state) => ({ ...state, [purchase.id]: !shown }))} className="flex items-center gap-1 text-xs font-bold text-blue-600">{shown ? <EyeOff size={14} /> : <Eye size={14} />}{shown ? "Hide" : "Show"}</button></div>{shown && <div className="mt-3 space-y-2">{fields(account).map(([label, value]) => <div key={label} className="flex items-start gap-2"><span className="w-16 shrink-0 pt-2 text-[10px] font-bold uppercase tracking-wide text-slate-400">{label}</span><span className="min-w-0 flex-1 break-all rounded-lg bg-slate-50 px-3 py-2 text-xs font-medium text-slate-800">{value}</span><button type="button" aria-label={`Copy ${label}`} onClick={() => copy(value)} className="mt-1.5 rounded-lg p-1.5 text-slate-400 hover:bg-slate-100 hover:text-blue-600"><Copy size={14} /></button></div>)}</div>}</div></motion.article>; })}</div>}</motion.section>;
}
